services:
  db:
    image: postgres:15
    container_name: notes_db
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
      POSTGRES_DB: notes_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: notes_backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=notes_user
      - DB_PASS=notes_pass
      - DB_NAME=notes_db
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: notes_frontend
    environment:
      - VITE_API_URL=http://backend:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data:
